# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "rn"
client_id = "a8d85a1ec5a1aa00cb08edd45e76f3d4"
application_url = "https://2bf9-106-51-65-216.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://2bf9-106-51-65-216.ngrok-free.app/auth/callback",
  "https://2bf9-106-51-65-216.ngrok-free.app/auth/shopify/callback",
  "https://2bf9-106-51-65-216.ngrok-free.app/api/auth/callback",
  "https://2bf9-106-51-65-216.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "react-node-form.myshopify.com"
