# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "NodeProject"
client_id = "8a6bffeba97da5ead75224a179b78e68"
application_url = "https://poly-controls-companion-snake.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://poly-controls-companion-snake.trycloudflare.com/auth/callback",
  "https://poly-controls-companion-snake.trycloudflare.com/auth/shopify/callback",
  "https://poly-controls-companion-snake.trycloudflare.com/api/auth/callback",
  "https://poly-controls-companion-snake.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "node-dev-online-store.myshopify.com"
