# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Contact-form-pop-up"
client_id = "31fb66c1b7c967032e011360ca7b2411"
application_url = "https://forward-combo-engagement-pensions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://forward-combo-engagement-pensions.trycloudflare.com/auth/callback",
  "https://forward-combo-engagement-pensions.trycloudflare.com/auth/shopify/callback",
  "https://forward-combo-engagement-pensions.trycloudflare.com/api/auth/callback",
  "https://forward-combo-engagement-pensions.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://seahorse-app-fstfy.ondigitalocean.app/api/webhooks"
  customer_data_request_url = "https://seahorse-app-fstfy.ondigitalocean.app/api/webhooks"
  shop_deletion_url = "https://seahorse-app-fstfy.ondigitalocean.app/api/webhooks"

[app_proxy]
url = "https://forward-combo-engagement-pensions.trycloudflare.com/userdata"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spiny-wheel.myshopify.com"
