# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shop-dash-node"
client_id = "2f51f75d47bf14f7bc81175e98cd0520"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
