# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "style"
client_id = "a0e537aa42d9fd3463b7e0dbee1d4509"
application_url = "https://vinyl-trip-simpsons-intensity.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://vinyl-trip-simpsons-intensity.trycloudflare.com/auth/callback",
  "https://vinyl-trip-simpsons-intensity.trycloudflare.com/auth/shopify/callback",
  "https://vinyl-trip-simpsons-intensity.trycloudflare.com/api/auth/callback",
  "https://vinyl-trip-simpsons-intensity.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "react-node-form.myshopify.com"
