# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "form-node-react"
client_id = "dc55cffa5be63f9dc795fcf9b6cba9cb"
application_url = "https://climb-popularity-grateful-instructional.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://climb-popularity-grateful-instructional.trycloudflare.com/auth/callback",
  "https://climb-popularity-grateful-instructional.trycloudflare.com/auth/shopify/callback",
  "https://climb-popularity-grateful-instructional.trycloudflare.com/api/auth/callback",
  "https://climb-popularity-grateful-instructional.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "react-node-form.myshopify.com"
